/*Name:Muzhou,Zhai  ID:10106810
 *CPSC 233-L01-T04
 *Version:Nov.11,2015 11:11pm
 * A event handlers (WindowListener) controls the window closing, hiding, and minimizing.
 */

//An extended version of java.awt.Frame that adds support for the JFC/Swing component architecture
import javax.swing.JFrame;
//An abstract adapter class for receiving window events. The methods in this class are empty. 
//This class exists as convenience for creating listener objects. 
import java.awt.event.WindowAdapter;
//Provides interfaces and classes for dealing with different types of events fired by AWT components
import java.awt.event.WindowEvent;

public class MyWindowListener extends WindowAdapter {
	/*A low-level event that indicates that a window has changed its status.
	 *  This low-level event is generated by a Window object when it is opened, closed, activated,
	 *   deactivated, iconified, or deiconified, or when focus is transfered into or out of the Window. 
	 */
     public void windowClosing(WindowEvent e){
    	 JFrame aFrame=(JFrame) e.getWindow();
    	 aFrame.setTitle("Closing Window...");
    	 
    	 //pause program so user can see the window text
    	 try{
    	     Thread.sleep(3000);
    	 }
    	 catch(InterruptedException ex){
    	     System.out.println("Pausing of program was interrupted");
    	 }
    	 aFrame.setVisible(false);
    	 aFrame.dispose();
     }
}
